### ISSUE TITLE
Error trying to export to mailbox when pst subfolders include invalid characters

### ISSUE THREAD

**Issue by dgottstein** [cjmach/pstconv#31]
Using the latest version (v0.9.6) I get this error:
```
Jul 10, 2023 12:35:18 PM pt.cjmach.pstconv.PstConverter error
SCHWERWIEGEND: Failed to convert PSTFile object for file java.io.RandomAccessFile@159a0f0e. Unable to create folder [C:\temp\mailbox\Oberste Ebene der Outlook-Datendatei.sbd\ABCD \ EFGH]
```
In the pst-archive there is an folder named "ABCD / EFGH".

Maybe those characters (like "\\" or "/") should be replaced by "_" or something before creating directories.

**Comment by cjmach** [comment]
Hi @dgottstein,

Thanks for reporting this issue. 
I checked the code and it's actually a bug. The fix was to apply the same logic already present when converting to EML.

**Comment by cjmach** [comment]
Just release version v0.9.6 with this bug fix. Closing this issue.
Thanks.
