### ISSUE TITLE
why not just put the jar file?

### ISSUE THREAD

**Issue by f1-outsourcing** [cjmach/pstconv#34]
I don't have java development environment on my computer.

**Comment by mwesten** [comment]
+1

**Comment by cjmach** [comment]
You don't need a java development environment on your computer, but you do need the Java Runtime Environment installed.

All releases are available as JARs that anyone can download. The current version is available on the following URL: https://github.com/cjmach/pstconv/packages/1199380

**Comment by f1-outsourcing** [comment]
Terribly sorry, I did not notice this packages. So used to getting this at releases :)

**Comment by mwesten** [comment]
Oh, sorry indeed! I was looking at the releases too ;)
